export const courses = [
    {
        id: 1,
        category: 'marketing',
        title: 'The Ultimate Google Ads Training Course',
        price: 100,
        author: 'Jerome Bell',
        image: 'course-1.jpg',
    },
    {
        id: 2,
        category: 'management',
        title: 'Product Management Fundamentals',
        price: 480,
        author: 'Marvin McKinney',
        image: 'course-2.jpg',
    },
    {
        id: 3,
        category: 'hr',
        title: 'HR Management and Analytics',
        price: 200,
        author: 'Leslie Alexander Li',
        image: 'course-3.jpg',
    },
    {
        id: 4,
        category: 'marketing',
        title: 'Brand Management & PR Communications',
        price: 530,
        author: 'Kristin Watson',
        image: 'course-4.jpg',
    },
    {
        id: 5,
        category: 'design',
        title: 'Graphic Design Basic',
        price: 500,
        author: 'Guy Hawkins',
        image: 'course-5.jpg',
    },
    {
        id: 6,
        category: 'management',
        title: 'Business Development Management',
        price: 400,
        author: 'Dianne Russell',
        image: 'course-6.jpg',
    },
    {
        id: 7,
        category: 'development',
        title: 'Highload Software Architecture',
        price: 600,
        author: 'Brooklyn Simmons',
        image: 'course-7.jpg',
    },
    {
        id: 8,
        category: 'hr',
        title: 'Human Resources – Selection and Recruitment',
        price: 150,
        author: 'Kathryn Murphy',
        image: 'course-8.jpg',
    },
    {
        id: 9,
        category: 'design',
        title: 'User Experience. Human-centered Design',
        price: 240,
        author: 'Cody Fisher',
        image: 'course-9.jpg',
    },
];